//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_18_20.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class espacio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public espacio()
        {
            this.fotoes = new HashSet<foto>();
        }
    
        public int ID { get; set; }
        public string direccion { get; set; }
        public Nullable<int> municipioID { get; set; }
        public Nullable<int> tipoEspacioID { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string descripcion { get; set; }
        public string inmuebles { get; set; }
        public string titulo { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<foto> fotoes { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual tipoEspacio tipoEspacio { get; set; }
    }
}
