//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_18_20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class foto
    {
        public int ID { get; set; }
        public string rutaimg { get; set; }
        public Nullable<int> espacioID { get; set; }
    
        public virtual espacio espacio { get; set; }
    }
}
